### ISSUE TITLE
Error while trying to mock open builtin function during tests

### ISSUE THREAD

**Issue by artmello** [oamg/leapp#336]
While writing tests for some actors that read data from files, we find a issue while trying to mock the builtin.open function. Here is what we have:

SampleActor:
```
from leapp.actors import Actor
from leapp.tags import SampleTag
from leapp.models import Output


class SampleFile(Actor):
    name = 'sample_file'
    description = 'Sample actor to read a file.'
    consumes = ()
    produces = (Output,)
    tags = (SampleTag,)

    def process(self):
        with open(self.get_file_path('sample.txt')) as f:
            self.produce(Output(data=f.read()))
```
OutputModel:
```
from leapp.models import Model, fields
from leapp.topics import SampleTopic


class Output(Model):
    topic = SampleTopic
    data = fields.String()
```

And the tests.py containing our single testcase:
```
from mock import patch, mock_open

from leapp.snactor.fixture import current_actor_context
from leapp.models import Output

def test_actor_execution(current_actor_context):
    sample_data = 'Burn the Witch!'
    with patch("__builtin__.open", mock_open(read_data=sample_data)) as mock_file:
        current_actor_context.run()
        assert current_actor_context.consume(Output)
        assert current_actor_context.consume(Output)[0].data == sample_data
```

This is our files structure:
```
.
├── actor.py
├── files
│   └── sample.txt
└── tests
    └── tests.py

2 directories, 3 files
```

When we try to execute the test running py.test, we got this:
```
============================= test session starts =============================
platform linux2 -- Python 2.7.15, pytest-3.6.4, py-1.5.4, pluggy-0.7.1
rootdir: /home/vagrant/mock_issue/actors/sampleactor/tests, inifile:
plugins: ordering-0.5, leapp-0.3
collected 1 item                                                              

tests.py F                                                              [100%]

================================== FAILURES ===================================
____________________________ test_actor_execution _____________________________

>   current_actor_context.run()

tests.py:46: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
/home/vagrant/devel/leapp-dev/lib/python2.7/site-packages/leapp/snactor/fixture.py:104: in run
    self._actor(messaging=self._messaging).run()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

>   .format(actorname=self.definition.name, exitcode=p.exitcode))
E   LeappRuntimeError: Actor sample_actor unexpectedly terminated with exit code: 1

/home/vagrant/devel/leapp-dev/lib/python2.7/site-packages/leapp/repository/actor_definition.py:67: LeappRuntimeError
---------------------------- Captured stderr call -----------------------------
Process Process-12:1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 267, in _bootstrap
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
  File "/home/vagrant/devel/leapp-dev/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 50, in _do_run
OSError: [Errno 9] Bad file descriptor
========================== 1 failed in 0.23 seconds ===========================
```

Some context, even if we are able to reproduce such issue on a brand new machine, at least in one single system this behaviour is not present and the test finishes as expected with a successful result. We are not able to specify what is the precisely difference between both. Also, if by any reason this is not the correct approach to test this kind of actor, any advice on the correct direction is welcomed (and maybe a good addition to documentation/tutorial)

**Comment by olysonek** [comment]
I think I ran into this too. I solved it using dependency injection - I pass a "read_file()" function to functions that need to read files and then mocking the "read_file()" function in tests:
https://github.com/oamg/leapp-repository/pull/186/commits/d5c51d33f5024d8683a6edf03df8d189d22959cf#diff-c8db401d29a7fbe6bf5f42c200158b03R43

**Comment by pirat89** [comment]
Closing the issue. It's hard to fix it in the framework, however it's possible to workaround it. Currently we suggest to put all code into private (actor's) libraries, so it's possible to mock everything when just the specific functions are called, instead of calling the actors itself (includes usually mock of the Actor class as well to provide working stuff for mocked API. See e.g.  the `testutils` library from [the *el7toel8* leapp repository](https://github.com/oamg/leapp-repository/blob/master/repos/system_upgrade/el7toel8/libraries/testutils.py) and possible [use in unit-tests](https://github.com/oamg/leapp-repository/blob/master/repos/system_upgrade/el7toel8/actors/targetuserspacecreator/tests/unit_test_targetuserspacecreator.py)

**Comment by pirat89** [comment]
Closing the issue. @vinzenz  feel free to reopen it and remove the label if you think we can & should fix it.
