### ISSUE TITLE
`snactor repo list` lists nothing

### ISSUE THREAD

**Issue by AloisMahdal** [oamg/leapp#396]
With leapp-repository installed, I tried to find out what repos I "have":

    snactor repo list
    snactor repo list --all

I tried the same from `/etc/leapp/repos.d/`, `/etc/leapp/repos.d/system_upgrade/`, `/etc/leapp/repos.d/system_upgrade/el7toel8`; I could not
get any listing from anywhere.

**Comment by vinzenz** [comment]
Did you actually register repositories by using snactor repo find?

**Comment by AloisMahdal** [comment]
No, I did not register anything.  Basically I just installed the packages and run the `snactor repo list` command.  There's no indication in doc that a registration should be done.

If it's indeed needed, it seems pretty counter-intuitive: I need to register items that I've just installed.

**Comment by jmikovic** [comment]
fixed in #436
