### ISSUE TITLE
Directories under /etc/yum/* need to make way for ../dnf symlinks after upgrade.

### ISSUE THREAD

**Issue by cwyamz** [oamg/leapp#399]
After preforming an upgrade from 7.6 to 8 using leapp the user is required to `dnf install yum` due to yum being in the to_remove file but the transaction fails:
Error unpacking rpm package yum-4.0.9-1.el8.noarch
"error: unpacking of archive failed on file /etc/yum/pluginconf.d: cpio: File from package already exists as a directory in system"

The work around is to rename /etc/yum to /etc/yum.bak and retry. 
More info here: https://bugzilla.redhat.com/show_bug.cgi?id=1626736#c9

libdnf-0.22.3-1.el8.x86_64
dnf-4.0.9-1.el8.noarch
leapp-0.4.0-1.el7_5.noarch

**Comment by pirat89** [comment]
Hi, this is known issue and it is issue of the yum which is not packaged correctly regarding the guidelines now.
