### ISSUE TITLE
Requiring packages instead of files in spec?

### ISSUE THREAD

**Issue by bocekm** [oamg/leapp#404]
Why do we require python six and setuptools modules as files instead of packages?

https://github.com/oamg/leapp/blob/87a7b74dfa2c9d1485afa1780f6c12e98df4d4b8/packaging/leapp.spec#L81

RHEL 7 has packages _python-six_ and _python-setuptools_ that contain these packages. Shouldn't we require those instead?

**Comment by vinzenz** [comment]
Yes RHEL7 has those, but RHEL8 does not have python-six nor python-setuptools but python2-six and python2-setuptools which do not 'provide' nor 'obsolete' the unversioned one.

This results in leapp being removed from during the upgrade or conflicting the upgrade. Using the file paths, allows us to workaround this problem until we have a  solution to the being removed problem.
