### ISSUE TITLE
Improve UX of Github Pages

### ISSUE THREAD

**Issue by bocekm** [oamg/leapp#418]
Update the GitHub Pages for Leapp [1] to fix the following issues which have been moved from the archived https://github.com/leapp-to/leapp-to.github.io/issues.

- [ ] Update the `title` element
The title element always contains text 'Leapp doc', no matter what page you are on. The suggestion is to append to the title name of the page you land on, eg on page https://leapp-to.github.io/actors the title should be 'Leapp doc - actors'

- [ ] Lines not wrapped/no horizontal scrollbar
When the width of the viewport is reduced below the width of the text, the lines are not wrapped nor a horizontal scrollbar appears.

- [ ] Hamburger button not working
When the viewport width is less than 768 px, the top menu with links is replaced by hamburger button. However on clicking it nothing happens and access to the links is lost.

[1] GitHub Pages for Leapp:
 - source: https://github.com/oamg/leapp/tree/gh-pages
- output: https://oamg.github.io/leapp/

**Comment by pirat89** [comment]
Closing as obsoleted. We are on readthedocs now and the github.io page just redirects people to https://leapp.readthedocs.io/en/latest/
