### ISSUE TITLE
snactor-generated scripts do not support Unicode

### ISSUE THREAD

**Issue by drehak** [oamg/leapp#440]
When no file encoding is specified, Python 2 regards .py files as `ascii`, compared to Python 3's `utf-8`. This leads to a fatal error in case of non-ascii characters, for example with the following actor body...
```
    def process(self):
        self.show_message("表ポあA鷗ŒéＢ逍Üßªąñ丂㐀𠀀")
```
...this error is thrown when trying to run the actor:
```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 26, in inspect_actor
    definition.load()
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 139, in load
    self._module = importer.find_module(name).load_module(name)
  File "/usr/lib64/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/root/Message/actors/message/actor.py", line 16
SyntaxError: Non-ASCII character '\xe8' in file /root/Message/actors/message/actor.py on line 16, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
Inspection of actor in actors/message failed
```
**Expected output:**
```
表ポあA鷗ŒéＢ逍Üßªąñ丂㐀𠀀
```

**Comment by vinzenz** [comment]
@bocekm i guess this rather is a thing for best practices don’t you think? Not really a bug per se

**Comment by bocekm** [comment]
Right, this behaviour is inherent to Python 2 (https://docs.python.org/2/howto/unicode.html). So I wouldn't probably even mention it in best practices.

The actor's code is supposed to be Python 2 and 3-compatible.  The solution is to add `# -*- coding: utf-8 -*-` to the first or second line of the source file. But even better, use ASCII only.

Even though I'm closing this issue, @drehak, you're welcome to write down counter-arguments. We can always reopen it.

**Comment by AloisMahdal** [comment]
The question is: *Do we want people to write actors in UTF-8 or choose their local encoding*?

Our expectation should be reflected in the template, so if we "want" UTF-8, then the generated files should be UTF-8 ready, ie. if we also expect people use python2, then the line should already be there.  (You don't necessarily even need to address that in best practices, assumption that everyone uses UTF-8 seems pretty safe these days.)

IMHO we should definitely want UTF-8.  I'm not even sure how python behaves if the file is unmarked; if it merely inherits runtime locale's encoding, then we could end up with mess of files that were written and tested with whatever locale, but are not marked.  So better ask for UTF-8 explicitly.

**Comment by AloisMahdal** [comment]
> how python2 behaves if the file is unmarked

well, Dominik actually mentions that in this case it was `ascii`, although I would not be 100% sure this is the whole story (programs are sometimes "smart" wrt encodings; it could be affected by `LC*` envvars and stuff).

**Comment by bocekm** [comment]
https://docs.python.org/2/howto/unicode.html: "If you don’t include such a comment, the default encoding used will be ASCII. ... Python 2.5 and higher are stricter and will produce a syntax error." - that's the syntax error @drehak has copied.

**Comment by bocekm** [comment]
Yeah, adding the `# -*- coding: utf-8 -*-` to the template is an option. Let's discuss it at Cabal.

**Comment by pirat89** [comment]
Actually that was what we have been thining earlier - to put the line into the template. However, from this point, the issue with non-ascii characters is effectively caught by CI (we can point the users or in case we will report it in future, they will be able to even fix that by them own). About the template - we do not want to put this line there by default (yes, keep it for cabal, just telling what we discussed with @vinzenz already). S no, we do not want to enable to people using of non-ascii encoding unless there is real reason for that - and in such case review, irc, mails,... works.

**Comment by drehak** [comment]
Have you reached any consensus on this?

**Comment by vinzenz** [comment]
@drehak nope, the cabal last week was skipped due to lack of topics. This one topic wasn't enough, we have another one planned for tomorrow.

**Comment by pirat89** [comment]
@drehak we decided that we will not support non-ascii characters in source code by default. Actually, we haven't found real big benefit to do such thing.
