### ISSUE TITLE
api.current_actor() returns None in tests

### ISSUE THREAD

**Issue by jmikovic** [oamg/leapp#452]
When trying to use api.get_actor_file_path() in test [0], test fails with error `
AttributeError: 'NoneType' object has no attribute 'get_actor_file_path'` [1]

[0] https://github.com/oamg/leapp-repository/commit/6fc1947236f2d73c39ddde55e5376e840c9950f8#diff-bfc2f0a6915aeb3ed0f0ccc73144638dR6
[1] http://pastebin.test.redhat.com/721950

**Comment by bocekm** [comment]
Have you run the test using `make test` or using _pytest_? If the latter, it's necessary to run it with setting the `LEAPP_TESTED_ACTOR` env var [1] - that injects the pytest testing environment with things from leapp framework.
[1] https://leapp.readthedocs.io/en/latest/unit-testing.html#running-the-tests

**Comment by pirat89** [comment]
It's expected to mock it nowadays as the proper fix on the leapp-framework side is more overkill (nowadays even more tricky than in the time this issue has been reported). Here is the generic mock class we use in the official leapp-repositories: https://github.com/oamg/leapp-repository/blob/6ec9f0adf2e9197e68a1919c1f69344fb0534eca/repos/system_upgrade/common/libraries/testutils.py#L70
