### ISSUE TITLE
RFE: stdlib - make possible to execute  commands with additional env

### ISSUE THREAD

**Issue by pirat89** [oamg/leapp#476]
Currently, we are not able to replace fully the subprocess library as the current imlementation of the `_call` function doesn't allow to pass additional env variables.

- [ ] modify the `run` function to accept the env parameter; when the param is not specified, use the env of the current process
- [ ] Modify the `_call` function to use `execvpe` instead of `execvp` and accept the `env` parameter

**Comment by jmikovic** [comment]
fixed by https://github.com/oamg/leapp/pull/481
