### ISSUE TITLE
`snactor run` exits with 0 despite CalledProcessError

### ISSUE THREAD

**Issue by AloisMahdal** [oamg/leapp#535]
`snactor run MyActor` now exits with 0 even if `MyActor` had a bad external command (CalledProcessError)

 *  leapp-0.7.0-1.201906241401Z.cfafac5.master.el7_6 passes,
 *  leapp-0.7.0-1.201907020939Z.54353bc.master.el7_6 fails.

So the primary suspect is #533.

---

This was caught by @drehak's downstream integration test `jats://redhat.com/oamg/leapp//sanity/system`:

    =============================================
    setup   test    diag    cleanup | case id
    --------------------------------|------------
    PASS    PASS    PASS    none    |  (1/12) Sys=c_ok,Es=zero
    PASS    PASS    PASS    none    |  (2/12) Sys=c_ok,Es=nonzero
    PASS    FAIL    PASS    none    |  (3/12) Sys=c_empty,Es=zero
    PASS    FAIL    PASS    none    |  (4/12) Sys=c_empty,Es=nonzero
    PASS    FAIL    PASS    none    |  (5/12) Sys=c_not_in_path,Es=zero
    PASS    FAIL    PASS    none    |  (6/12) Sys=c_not_in_path,Es=nonzero
    PASS    PASS    PASS    none    |  (7/12) Sys=s_ok,Es=zero
    PASS    PASS    PASS    none    |  (8/12) Sys=s_ok,Es=nonzero
    PASS    FAIL    PASS    none    |  (9/12) Sys=s_not_executable,Es=zero
    PASS    FAIL    PASS    none    | (10/12) Sys=s_not_executable,Es=nonzero
    PASS    FAIL    PASS    none    | (11/12) Sys=s_not_found,Es=zero
    PASS    FAIL    PASS    none    | (12/12) Sys=s_not_found,Es=nonzero
    =============================================

For example, cases like this:

    snactor run Runner                                      FAIL
    {'r.es': '0', 'o.es_expr': '1', 't.cmd': 'snactor run Runner'}

that expect non-zero exit status (`o.es_expr`), get 0 (`r.es`).

**Comment by vinzenz** [comment]
Fixed with #536
