### ISSUE TITLE
Old reporting API is used in actor-rhel7-to-rhel8.md

### ISSUE THREAD

**Issue by olysonek** [oamg/leapp#556]
The old, removed function `report_with_remediation` is being used in some example code in docs/source/actor-rhel7-to-rhel8.md. The example code should be ported to the new API.

**Comment by Rezney** [comment]
Thanks for reporting this. This was planned to fix but got delayed.

Here is PR:

https://github.com/oamg/leapp/pull/557

**Comment by Rezney** [comment]
Fixed
