### ISSUE TITLE
RFE: add a check to make sure actor can consume a message

### ISSUE THREAD

**Issue by Rezney** [oamg/leapp#562]
This is related to https://github.com/oamg/leapp-repository/issues/334

In case there is an actor which consumes a message which will be created in the next phase, we should issue a warning / raise an exception.

**Comment by Rezney** [comment]
https://github.com/oamg/leapp/pull/564 should handle the issue...

**Comment by pirat89** [comment]
The #564 PR has been merged. Closing the issue.
