### ISSUE TITLE
leapp/snactor/fixture.py is not compatible with py3

### ISSUE THREAD

**Issue by ZhukovGreen** [oamg/leapp#629]
https://github.com/oamg/leapp/blob/430ac840d60f83ef716edd585933d9b7df4846b4/leapp/snactor/fixture.py#L56
```
E           AttributeError: 'function' object has no attribute 'func_code'
```
This makes any exception happened during the testing of actors unreadable

**Comment by fellipeh** [comment]
@ZhukovGreen  leapp and leapp-repository need to be compatible with both python (py2 and py3), on leapp-repository we use `six.PY3` to check it, since six package is one of the requirements..

**Comment by ZhukovGreen** [comment]
@fellipeh I tried to fix it with just func.__code__ , but then it staked with other issue somewehre when initializing TypeCode here:
https://github.com/oamg/leapp/blob/430ac840d60f83ef716edd585933d9b7df4846b4/leapp/snactor/fixture.py#L20-L34

so I gave up for a while, and decided to report:)
