### ISSUE TITLE
Stop importing cockpit's base1/patternfly.css

### ISSUE THREAD

**Issue by KKoukiou** [oamg/leapp#642]
This is deprecated API and will be dropped at some point, in  of projects shipping their own CSS.
    
Follow https://github.com/cockpit-project/starter-kit/blob/master/webpack.config.js approach on how to use PF CSS.

(I notice that you don't use webpack for bundling your project so that might need a different approach from the starter-kit)

**Comment by martinpitt** [comment]
Please see the [announcement](https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/thread/2Q6AAQXGI5IE5D7XMTJUIKP3NIS3CIBL/) for some details and links.

**Comment by vinzenz** [comment]
Thanks, we will drop the cockpit code using this here as this is no longer in use for years and totally outdated.
