### ISSUE TITLE
Deprecated decorated is not covered by tests

### ISSUE THREAD

**Issue by ZhukovGreen** [oamg/leapp#643]
Based on coverage report the MR https://github.com/oamg/leapp/pull/640
is not covered by tests.

```
----------- coverage: platform linux, python 3.8.3-final-0 -----------
Name                                              Stmts   Miss  Cover   Missing
-------------------------------------------------------------------------------
leapp/utils/deprecation.py                           64     52    19%   22-41, 63-114
```

**Comment by vinzenz** [comment]
Actually it might be a fluke in the detection

We have testing repos in tests/data that contain certain code for testing it

**Comment by ZhukovGreen** [comment]
@vinzenz thx for pointing out. Investigating this

**Comment by ZhukovGreen** [comment]
hey @vinzenz, could you please point me out what I am doing wrong.  I am running tests via `make test`. Also I found out that travis also not testing the deprecation.py module, at least what I see here (https://travis-ci.org/github/oamg/leapp/jobs/700842579#L758).

**Comment by vinzenz** [comment]
I figured out what is going on, I missed in the commit the actual test_deprecation.py to be committed. Will create it.
