### ISSUE TITLE
Impossible to run tests as non-root user

### ISSUE THREAD

**Issue by pirat89** [oamg/leapp#646]
**Actual behavior**
Currently it is not possible to run tests as non-root user, nor to install deps / prep env. as non-root user.
In case I want to run unit-tests locally:
- installation of deps via `make test` is impossible (pip installation on the host system is not acceptable)
- installation of deps via `make install-deps-container` is impossible (docker requires to be run as root)

**Expected behavior**
- ability to install deps into the pyenv environment
- use of `podman` for containers
  - in this case, it could be done via envar; by default it could be still docker, but it should be possible to excute podman instead; e.g.: `CONTAINER_UTIL=podman make install-deps-container; CONTAINER_UTIL=podman make container-test;` ....

**System information (please complete the following information):**
- Fedora 31

**Additional info:**
To make it clear, the possibility to run everything using `podman` could be enough. It's not required to transform everything, but there should be at least one possible way to run tests without needs of root powers.

**Comment by pirat89** [comment]
@ZhukovGreen  I think you could like this one :-) It still needs a task in our jira.

**Comment by ZhukovGreen** [comment]
@pirat89 ok, I will take a look. I will create a ticket in jira a well

**Comment by ZhukovGreen** [comment]
I think there is something in Makefile, since I am successfully running tests in this repo without being a root. But I am not using makefile for this. Just virtualenv @pirat89

**Comment by pirat89** [comment]
@ZhukovGreen Definitely this ticket is only about changes in the Makefile.
