### ISSUE TITLE
Simplify the documentation related to the deprecation process

### ISSUE THREAD

**Issue by zhukovgreen** [oamg/leapp#663]
Ref #653 

TODO:
- [x] Solve code review https://github.com/oamg/leapp/pull/653#pullrequestreview-484749835
- [ ] split the deprecation doc into parts (tutorial, generica info, ...) and put it into the right places so people can find it intuitively
   - do not forget about contribution & coding guidelines
- [ ] specify better what is covered by deprecation process
- [ ] https://github.com/oamg/leapp/pull/653#discussion_r466940574
- [ ] https://github.com/oamg/leapp/pull/653#discussion_r468549881
- [ ] https://github.com/oamg/leapp/pull/653#discussion_r485422069
- [ ] consider remove the "Additional various outputs of snactor and leapp" bottom part of the doc, or consolidate it....
- [ ] explain better the use of the `stack_level_offset` parameter of the `@deprecated` decorator.
- [ ] Fix supress_deprecation decorator to handle generators (`yield`) as well or document the limitation

**Comment by pirat89** [comment]
Just a note, that it's problematic to suppress deprecation for generators directly. The deprecation has to be in such a case suppressed now one level above the generator. E.g. this will not work:
```python
@suppress_deprecation(Foo)
def Bar():
    for i in range(5):
        yield Foo(val=i)
```

But this works:
```python
def bar():
    for i in range(5):
        yield Foo(val=i)

@suppress_deprecation(Foo)
def foobar():
    return list(*bar())
```
