### ISSUE TITLE
'leapp upgrade' from CentOS 7.x to Alma 8.5 stops with error 'Disk Requirements' on XFS-Filesystem

### ISSUE THREAD

**Issue by maze-m** [oamg/leapp#778]
**Actual behavior**
When I try do do an Upgrade from CentOS 7.x to Alma 8.5 as it's discribed in the [ELevate Quickstart Guide](https://wiki.almalinux.org/elevate/ELevate-quickstart-guide.html) from Alma Linux I got the 'Error Summary - Disk Requirements: At least X MB more space needed on the </XXX> filesystem'. 
I got this error although there's enough space left on device for doing an upgrade.

**To Reproduce**
Steps to reproduce the behavior

1. 'yum update -y' on CentOS 7.x machine
2. 'reboot' CentOS 7.x machine
3. Install 'elevate-release' Repo: 'sudo yum install -y http://repo.almalinux.org/elevate/elevate-release-latest-el7.noarch.rpm'
4. 'leapp preupgrade'
5. 'rmmod pata_acpi' && 'echo PermitRootLogin yes | sudo tee -a /etc/ssh/sshd_config' && 'leapp answer --section remove_pam_pkcs11_module_check.confirm=True'

6. 'leapp upgrade'
7. See error:

```
installing package libattr-2.4.48-3.el8.i686 needs 171MB on the / filesystem
  installing package pcre-8.42-6.el8.i686 needs 171MB on the / filesystem
  installing package nss-softokn-freebl-3.67.0-7.el8_5.i686 needs 172MB on the / filesystem

Error Summary
-------------
Disk Requirements:
   At least 226MB more space needed on the / filesystem.



============================================================
                       END OF ERRORS                        
============================================================


Debug output written to /var/log/leapp/leapp-upgrade.log

============================================================
                           REPORT                           
============================================================

A report has been generated at /var/log/leapp/leapp-report.json
A report has been generated at /var/log/leapp/leapp-report.txt

============================================================
                       END OF REPORT                        
============================================================

Answerfile has been generated at /var/log/leapp/answerfile
```

   

**Expected behavior**
Although I've resized my /-partition as it's discribed [here ](https://access.redhat.com/solutions/5057391), I got the error 'At least X MB more space needed on the </XXX> filesystem' anymore on XFS-based FS. 
Is it possible to comment out the check of Disk-Space?

**System information (please complete the following information):**

- OS and version: CentOS Linux release 7.9.2009 (Core)
- `# uname -a`: Linux dev.intern.blabla.com 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- `# rpm -qa "*leapp*"` (or shorthashes of commits in case of manual installation):

```
# rpm -qa "leapp*"
dev.intern.blabla.com:~$ rpm -qa "*leapp*"
leapp-deps-0.12.1-100.20210924142320684911.master.28.g1f03432.el7.noarch
leapp-upgrade-el7toel8-0.14.0-100.202109271224Z.b7ebfca.master.el7.elevate.noarch
leapp-upgrade-el7toel8-deps-0.14.0-100.202109271224Z.b7ebfca.master.el7.elevate.noarch
leapp-0.12.1-100.20210924142320684911.master.28.g1f03432.el7.noarch
python2-leapp-0.12.1-100.20210924142320684911.master.28.g1f03432.el7.noarch
leapp-data-almalinux-0.1-4.el7.noarch
```

Attach (or provide link to) log files if applicable (optional - may contain confidential information):

- *All files in /var/log/leapp/*:

`dev.intern.blabla.com:~$ ll /var/log/leapp/
total 3424
-rw-r--r-- 1 root root       0 Jun  9 10:54 answerfile
-rw-r--r-- 1 root root      49 Jun  9 10:54 answerfile.userchoices
drwxr-xr-x 2 root root    4096 Jun  9 09:18 archive
-rw-r--r-- 1 root root   20017 Jun  9 09:25 dnf-plugin-data.txt
-rw-r--r-- 1 root root  236750 Jun  9 10:54 leapp-report.json
-rw-r--r-- 1 root root  228078 Jun  9 10:54 leapp-report.txt
-rw-r--r-- 1 root root 3010206 Jun  9 10:54 leapp-upgrade.log
dev.intern.blabla.com:~$ `

**Comment by pirat89** [comment]
@maze-m Hi. thank you for the report.

> Although I've resized my /-partition as it's discribed here 

The document is not speaking just about resizing / partition. It's speaking mainly about
* resize /var partition
* set LEAPP_OVL_SIZE envar when XFS without ftype attribute is present on the system

One of above methods is fixing this issue. Article is also explaining why you are interested about /var instead of just / (in case /var is on separate partition).

> Is it possible to comment out the check of Disk-Space?

No. It's standard check & test done by RPM for any rpm transaction that cannot be skipped.

> All files in /var/log/leapp/:
dev.intern.blabla.com:~$ ll /var/log/leapp/ total 3424 -rw-r--r-- 1 root root 0 Jun 9 10:54 answerfile -rw-r--r-- 1 root root 49 Jun 9 10:54 answerfile.userchoices drwxr-xr-x 2 root root 4096 Jun 9 09:18 archive -rw-r--r-- 1 root root 20017 Jun 9 09:25 dnf-plugin-data.txt -rw-r--r-- 1 root root 236750 Jun 9 10:54 leapp-report.json -rw-r--r-- 1 root root 228078 Jun 9 10:54 leapp-report.txt -rw-r--r-- 1 root root 3010206 Jun 9 10:54 leapp-upgrade.log dev.intern.blabla.com:~$
