### ISSUE TITLE
how to excluding a package during the upgrade process.

### ISSUE THREAD

**Issue by skull-Atul** [oamg/leapp#856]
I am trying to upgrade Centos 7 to Rocky Linux 8. My environment has its own complied Apache package once the upgrade process and the reboot all the files related to Apache are deleted.

Is there any way to tell Leapp to exclude the particular package

**Comment by pirat89** [comment]
Hi, yes, you can find the answer for this and other similar questions in the [discussion](https://github.com/oamg/leapp-repository/discussions/1192) in [leapp-repository](https://github.com/oamg/leapp-repository).

Transferring to the right repository.
