### ISSUE TITLE
Keep Leapp in MacOS menu bar

### ISSUE THREAD

**Issue by yoyomo** [oamg/leapp#868]
**Actual behavior**
When I close/quit the desktop application, it also removes it from the menu bar
There are other applications like Docker desktop or ChatGPT that provide a way to keep the app running only in the menu bar

**To Reproduce**
Steps to reproduce the behavior

1. Quit application

**Expected behavior**
Keep the application running in the menu bar, until this one is quit or specified otherwise in the settings.

**System information (please complete the following information):**

- MacOS 14.5 (23F79)
- Leapp Version 0.26.1 (0.26.1)

****

**Additional context**
<img width="128" alt="Screenshot 2024-06-27 at 11 32 03" src="https://github.com/oamg/leapp/assets/12818568/837a8075-4068-4d70-a380-acce40f8bdda">
<img width="280" alt="Screenshot 2024-06-27 at 11 31 57" src="https://github.com/oamg/leapp/assets/12818568/0f7f8c84-b348-4807-8eda-249435e0afb4">

**Comment by pirat89** [comment]
@yoyomo  hi :) thank you for the report, but you are looking for different application :) Leapp is framework and also command line utility, used on Linux. Actual version of the application is 0.17.0.

**Comment by yoyomo** [comment]
omg I did not notice sorry! thank you for letting me know
